//! Markdown reporter plugin.
//!
//! Generates a Markdown-formatted test report suitable for
//! embedding in READMEs, GitHub PR comments, or CI artifacts.

use std::fmt::Write;
use std::time::Duration;

use crate::adapters::{TestRunResult, TestStatus};
use crate::error;
use crate::events::TestEvent;
use crate::plugin::Plugin;

/// Escape text for safe use in Markdown table cells and headings.
fn md_escape(s: &str) -> String {
    s.replace('|', "\\|")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('[', "\\[")
        .replace(']', "\\]")
}

/// Markdown reporter configuration.
#[derive(Debug, Clone)]
pub struct MarkdownConfig {
    /// Output file path (None = stdout)
    pub output_path: Option<String>,
    /// Whether to include individual test details
    pub include_details: bool,
    /// Whether to include the timestamp header
    pub include_timestamp: bool,
    /// Maximum number of slowest tests to show
    pub show_slowest: usize,
    /// Whether to show error messages for failed tests
    pub show_errors: bool,
}

impl Default for MarkdownConfig {
    fn default() -> Self {
        Self {
            output_path: None,
            include_details: true,
            include_timestamp: true,
            show_slowest: 5,
            show_errors: true,
        }
    }
}

/// Markdown reporter plugin.
pub struct MarkdownReporter {
    config: MarkdownConfig,
    output: String,
}

impl MarkdownReporter {
    pub fn new(config: MarkdownConfig) -> Self {
        Self {
            config,
            output: String::new(),
        }
    }

    /// Get the generated markdown output.
    pub fn output(&self) -> &str {
        &self.output
    }
}

impl Plugin for MarkdownReporter {
    fn name(&self) -> &str {
        "markdown"
    }

    fn version(&self) -> &str {
        "1.0.0"
    }

    fn on_event(&mut self, _event: &TestEvent) -> error::Result<()> {
        Ok(())
    }

    fn on_result(&mut self, result: &TestRunResult) -> error::Result<()> {
        self.output = generate_markdown(result, &self.config);
        Ok(())
    }
}

/// Generate a complete Markdown report from test results.
pub fn generate_markdown(result: &TestRunResult, config: &MarkdownConfig) -> String {
    let mut md = String::with_capacity(4096);

    // Header
    write_header(&mut md, result, config);

    // Summary table
    write_summary(&mut md, result);

    // Suite details
    if config.include_details {
        write_suite_details(&mut md, result, config);
    }

    // Failures section
    if config.show_errors && result.total_failed() > 0 {
        write_failures(&mut md, result);
    }

    // Slowest tests
    if config.show_slowest > 0 {
        write_slowest(&mut md, result, config.show_slowest);
    }

    md
}

fn write_header(md: &mut String, result: &TestRunResult, config: &MarkdownConfig) {
    let status_icon = if result.is_success() {
        " PASS"
    } else {
        " FAIL"
    };

    let _ = writeln!(md, "# Test Results");
    md.push('\n');

    if config.include_timestamp {
        let _ = writeln!(md, "> Generated by testx");
        md.push('\n');
    }

    let _ = writeln!(
        md,
        "**Status**: {} | **Total**: {} | **Passed**: {} | **Failed**: {} | **Skipped**: {} | **Duration**: {}",
        status_icon,
        result.total_tests(),
        result.total_passed(),
        result.total_failed(),
        result.total_skipped(),
        format_duration(result.duration),
    );
    md.push('\n');
}

fn write_summary(md: &mut String, result: &TestRunResult) {
    if result.suites.len() <= 1 {
        return;
    }

    let _ = writeln!(md, "## Suites Overview");
    md.push('\n');
    let _ = writeln!(md, "| Suite | Tests | Passed | Failed | Skipped | Status |");
    let _ = writeln!(md, "| ----- | ----- | ------ | ------ | ------- | ------ |");

    for suite in &result.suites {
        let status_icon = if suite.is_passed() { "✅" } else { "❌" };
        let _ = writeln!(
            md,
            "| {} | {} | {} | {} | {} | {} |",
            md_escape(&suite.name),
            suite.tests.len(),
            suite.passed(),
            suite.failed(),
            suite.skipped(),
            status_icon,
        );
    }
    md.push('\n');
}

fn write_suite_details(md: &mut String, result: &TestRunResult, config: &MarkdownConfig) {
    let _ = writeln!(md, "## Test Details");
    md.push('\n');

    for suite in &result.suites {
        let icon = if suite.is_passed() { "✅" } else { "❌" };
        let _ = writeln!(
            md,
            "### {} {} ({} tests)",
            icon,
            md_escape(&suite.name),
            suite.tests.len()
        );
        md.push('\n');

        let _ = writeln!(md, "| Test | Status | Duration |");
        let _ = writeln!(md, "| ---- | ------ | -------- |");

        for test in &suite.tests {
            let (icon, status) = match test.status {
                TestStatus::Passed => ("", "Pass"),
                TestStatus::Failed => ("", "Fail"),
                TestStatus::Skipped => ("⏭️", "Skip"),
            };
            let _ = writeln!(
                md,
                "| {} | {} {} | {} |",
                md_escape(&test.name),
                icon,
                status,
                format_duration(test.duration),
            );
        }
        md.push('\n');

        // Show inline errors if configured
        if config.show_errors {
            for test in suite.failures() {
                if let Some(ref error) = test.error {
                    let _ = writeln!(md, "<details>");
                    let _ = writeln!(md, "<summary> {} — Error</summary>", md_escape(&test.name));
                    md.push('\n');
                    let _ = writeln!(md, "```");
                    let _ = writeln!(md, "{}", error.message);
                    if let Some(ref loc) = error.location {
                        let _ = writeln!(md, "at {loc}");
                    }
                    let _ = writeln!(md, "```");
                    let _ = writeln!(md, "</details>");
                    md.push('\n');
                }
            }
        }
    }
}

fn write_failures(md: &mut String, result: &TestRunResult) {
    let _ = writeln!(md, "## Failures");
    md.push('\n');

    for suite in &result.suites {
        for test in suite.failures() {
            let _ = writeln!(
                md,
                "###  {}::{}",
                md_escape(&suite.name),
                md_escape(&test.name)
            );
            md.push('\n');
            if let Some(ref error) = test.error {
                let _ = writeln!(md, "```");
                let _ = writeln!(md, "{}", error.message);
                if let Some(ref loc) = error.location {
                    let _ = writeln!(md, "at {loc}");
                }
                let _ = writeln!(md, "```");
                md.push('\n');
            }
        }
    }
}

fn write_slowest(md: &mut String, result: &TestRunResult, n: usize) {
    let slowest = result.slowest_tests(n);
    if slowest.is_empty() {
        return;
    }

    let _ = writeln!(md, "## Slowest Tests");
    md.push('\n');
    let _ = writeln!(md, "| # | Test | Suite | Duration |");
    let _ = writeln!(md, "| - | ---- | ----- | -------- |");

    for (i, (suite, test)) in slowest.iter().enumerate() {
        let _ = writeln!(
            md,
            "| {} | {} | {} | {} |",
            i + 1,
            md_escape(&test.name),
            md_escape(&suite.name),
            format_duration(test.duration),
        );
    }
    md.push('\n');
}

fn format_duration(d: Duration) -> String {
    let ms = d.as_millis();
    if ms == 0 {
        "<1ms".to_string()
    } else if ms < 1000 {
        format!("{ms}ms")
    } else {
        format!("{:.2}s", d.as_secs_f64())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::adapters::{TestCase, TestError, TestSuite};

    fn make_test(name: &str, status: TestStatus, ms: u64) -> TestCase {
        TestCase {
            name: name.into(),
            status,
            duration: Duration::from_millis(ms),
            error: None,
        }
    }

    fn make_failed_test(name: &str, ms: u64, msg: &str) -> TestCase {
        TestCase {
            name: name.into(),
            status: TestStatus::Failed,
            duration: Duration::from_millis(ms),
            error: Some(TestError {
                message: msg.into(),
                location: Some("test.rs:10".into()),
            }),
        }
    }

    fn make_result() -> TestRunResult {
        TestRunResult {
            suites: vec![
                TestSuite {
                    name: "math".into(),
                    tests: vec![
                        make_test("test_add", TestStatus::Passed, 10),
                        make_test("test_sub", TestStatus::Passed, 20),
                        make_failed_test("test_div", 5, "division by zero"),
                    ],
                },
                TestSuite {
                    name: "strings".into(),
                    tests: vec![
                        make_test("test_concat", TestStatus::Passed, 15),
                        make_test("test_upper", TestStatus::Skipped, 0),
                    ],
                },
            ],
            duration: Duration::from_millis(500),
            raw_exit_code: 1,
        }
    }

    #[test]
    fn markdown_header() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("# Test Results"));
        assert!(md.contains(" FAIL"));
        assert!(md.contains("**Total**: 5"));
        assert!(md.contains("**Passed**: 3"));
        assert!(md.contains("**Failed**: 1"));
        assert!(md.contains("**Skipped**: 1"));
    }

    #[test]
    fn markdown_pass_status() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "t".into(),
                tests: vec![make_test("t1", TestStatus::Passed, 1)],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains(" PASS"));
    }

    #[test]
    fn markdown_suites_overview() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("## Suites Overview"));
        assert!(md.contains("| math |"));
        assert!(md.contains("| strings |"));
    }

    #[test]
    fn markdown_test_details() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("## Test Details"));
        assert!(md.contains("| test_add |"));
        assert!(md.contains("| test_div |"));
    }

    #[test]
    fn markdown_failures_section() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("## Failures"));
        assert!(md.contains("division by zero"));
    }

    #[test]
    fn markdown_no_failures_no_section() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "t".into(),
                tests: vec![make_test("t1", TestStatus::Passed, 1)],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(!md.contains("## Failures"));
    }

    #[test]
    fn markdown_slowest() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("## Slowest Tests"));
    }

    #[test]
    fn markdown_no_details() {
        let config = MarkdownConfig {
            include_details: false,
            ..Default::default()
        };
        let md = generate_markdown(&make_result(), &config);
        assert!(!md.contains("## Test Details"));
    }

    #[test]
    fn markdown_duration_format() {
        assert_eq!(format_duration(Duration::ZERO), "<1ms");
        assert_eq!(format_duration(Duration::from_millis(42)), "42ms");
        assert_eq!(format_duration(Duration::from_millis(1500)), "1.50s");
    }

    #[test]
    fn markdown_plugin_trait() {
        let mut reporter = MarkdownReporter::new(MarkdownConfig::default());
        assert_eq!(reporter.name(), "markdown");
        assert_eq!(reporter.version(), "1.0.0");

        reporter.on_result(&make_result()).unwrap();
        assert!(reporter.output().contains("# Test Results"));
    }

    #[test]
    fn markdown_error_location() {
        let md = generate_markdown(&make_result(), &MarkdownConfig::default());
        assert!(md.contains("test.rs:10"));
    }

    #[test]
    fn markdown_single_suite_no_overview() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "single".into(),
                tests: vec![make_test("t", TestStatus::Passed, 1)],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(!md.contains("## Suites Overview")); // only 1 suite
    }

    // ─── Edge Case Tests ────────────────────────────────────────────────

    #[test]
    fn markdown_empty_result() {
        let result = TestRunResult {
            suites: vec![],
            duration: Duration::ZERO,
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("# Test Results"));
        assert!(md.contains("**Total**: 0"));
        assert!(md.contains(" PASS")); // 0 failed = pass
    }

    #[test]
    fn markdown_all_skipped() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "skip-suite".into(),
                tests: vec![
                    make_test("s1", TestStatus::Skipped, 0),
                    make_test("s2", TestStatus::Skipped, 0),
                ],
            }],
            duration: Duration::from_millis(5),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("**Skipped**: 2"));
        assert!(md.contains("**Passed**: 0"));
        assert!(!md.contains("## Failures"));
    }

    #[test]
    fn markdown_no_timestamp() {
        let config = MarkdownConfig {
            include_timestamp: false,
            ..Default::default()
        };
        let md = generate_markdown(&make_result(), &config);
        assert!(!md.contains("Generated by testx"));
    }

    #[test]
    fn markdown_no_errors_shown() {
        let config = MarkdownConfig {
            show_errors: false,
            ..Default::default()
        };
        let md = generate_markdown(&make_result(), &config);
        assert!(!md.contains("## Failures"));
        assert!(!md.contains("<details>"));
    }

    #[test]
    fn markdown_zero_slowest() {
        let config = MarkdownConfig {
            show_slowest: 0,
            ..Default::default()
        };
        let md = generate_markdown(&make_result(), &config);
        assert!(!md.contains("## Slowest Tests"));
    }

    #[test]
    fn markdown_large_slowest_limit() {
        let config = MarkdownConfig {
            show_slowest: 100, // more than available
            ..Default::default()
        };
        let md = generate_markdown(&make_result(), &config);
        // Should still show section with available tests
        assert!(md.contains("## Slowest Tests"));
    }

    #[test]
    fn markdown_special_chars_in_names() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "suite<special>&\"chars\"".into(),
                tests: vec![make_test("test|pipe|name", TestStatus::Passed, 1)],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        // Markdown doesn't need HTML escaping but names should be present
        assert!(md.contains("pipe"));
    }

    #[test]
    fn markdown_very_long_duration() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "t".into(),
                tests: vec![make_test("slow", TestStatus::Passed, 600_000)], // 10 minutes
            }],
            duration: Duration::from_secs(600),
            raw_exit_code: 0,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("600.00s"));
    }

    #[test]
    fn markdown_plugin_on_event_is_noop() {
        let mut r = MarkdownReporter::new(MarkdownConfig::default());
        assert!(
            r.on_event(&crate::events::TestEvent::Warning {
                message: "x".into()
            })
            .is_ok()
        );
        assert!(r.output().is_empty());
    }

    #[test]
    fn markdown_plugin_shutdown() {
        let mut r = MarkdownReporter::new(MarkdownConfig::default());
        assert!(r.shutdown().is_ok());
    }

    #[test]
    fn markdown_multiple_failures_different_suites() {
        let result = TestRunResult {
            suites: vec![
                TestSuite {
                    name: "a".into(),
                    tests: vec![make_failed_test("f1", 1, "err1")],
                },
                TestSuite {
                    name: "b".into(),
                    tests: vec![make_failed_test("f2", 2, "err2")],
                },
            ],
            duration: Duration::from_millis(10),
            raw_exit_code: 1,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("a::f1"));
        assert!(md.contains("b::f2"));
        assert!(md.contains("err1"));
        assert!(md.contains("err2"));
    }

    #[test]
    fn markdown_error_without_location() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "s".into(),
                tests: vec![TestCase {
                    name: "t".into(),
                    status: TestStatus::Failed,
                    duration: Duration::from_millis(1),
                    error: Some(TestError {
                        message: "no loc".into(),
                        location: None,
                    }),
                }],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 1,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("no loc"));
    }

    #[test]
    fn markdown_suite_with_all_status_types() {
        let result = TestRunResult {
            suites: vec![TestSuite {
                name: "mixed".into(),
                tests: vec![
                    make_test("pass", TestStatus::Passed, 1),
                    make_failed_test("fail", 2, "oops"),
                    make_test("skip", TestStatus::Skipped, 0),
                ],
            }],
            duration: Duration::from_millis(10),
            raw_exit_code: 1,
        };
        let md = generate_markdown(&result, &MarkdownConfig::default());
        assert!(md.contains("Pass"));
        assert!(md.contains("Fail"));
        assert!(md.contains("Skip"));
    }
}
